version: "3.1"
services:
  wordpress:
    image: newfc/wordpress:1.0.0
    restart: unless-stopped
    depends_on:
      - mysql-wordpress
    ports:
      - 80:80
    env_file:
      - ./.env
    environment:
      - WORDPRESS_DB_HOST=mysql-wordpress
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
#  browsersync:
#    depends_on:
#      - wordpress
#    build:
#      context: ./src
#      dockerfile: ../Dockerfile
#    restart: unless-stopped
#    links:
#      - wordpress:${SITE_URL}
#    env_file:
#      - ./.env
#    ports:
#      - 3000:3000
#      - 3001:3001
#    volumes:
#      - ./src/themes/:/var/www/html/themes
#      - ./src/gulp/gulp-tasks:/var/www/html/gulp/gulp-tasks
#      - ./src/gulpfile.js:/var/www/html/gulpfile.js
#    command: "npm run watch"
  mysql-wordpress:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./src/initial-db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    command: "--default-authentication-plugin=mysql_native_password"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-wordpress:db
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
